### ISSUE TITLE
Part I: Theorie

### ISSUE THREAD

**Issue by manuelroth** [osm2vectortiles/bachelor-thesis#11]
Describe the most important concepts used in our thesis:
- What are Vector Tiles? (Reference study thesis)
- TM2Source / Mapnik for Vector Tile creation
- Imposm3 / PostGIS

**Comment by lukasmartinelli** [comment]
A understanding of the entire XYZ mechanism is also important (4-5 sentences http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames)

**Comment by lukasmartinelli** [comment]
## Mask Zoom Level
- [ ] Wie funktioniert das?
